
  - name: Slack | Check if is present
    command: dpkg-query -W slack
    register: slack_present
    become: yes
    failed_when: slack_present.rc > 1
    changed_when: slack_present.rc == 1
    tags:
      - slack

  - name: Slack | download package
    get_url:
      url="https://slack-ssb-updates.global.ssl.fastly.net/linux_releases/slack-desktop-1.2.5-amd64.deb"
      dest="/tmp/slack_desktop.deb"
    when: slack_present.rc == 1
    tags:
      - slack

  - name: Slack | install package
    apt: deb="/tmp/slack_desktop.deb"
    become: true
    when: slack_present.rc == 1
    tags:
      - slack
