---
- name: Add apt keys
  apt_key: keyserver=keyserver.ubuntu.com id={{ spotify.apt_key.id }}

- name: Add repository
  apt_repository: repo='deb http://repository.spotify.com stable non-free'

- name: Install spotify
  apt: name=spotify-client update_cache=yes state=latest
